default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password:

development:
  <<: *default
  database: github_users_development

test:
  <<: *default
  database: github_users_test

production:
  url: <%= ENV['DATABASE_URL'] %>
